name: Test Binance API Access

on:
  workflow_dispatch:

jobs:
  test_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run Binance API test script
        run: python test_binance_api.py
